#!/bin/sh

# Increase key speed via a rate change
xset r rate 300 50

setxkbmap -layout se -option caps:super

killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'

xset -q | grep "Caps lock:\s*on" && xdotool key Caps_Lock
