#!/bin/sh
battery="/sys/class/power_supply/BAT0"
capacity=$(cat "$battery/capacity")

case "$(cat "$battery/status")" in
		"Full") status="" ;;
		"Discharging") status="-" ;;
		"Charging") status="+" ;;
		"Not charging") status="x" ;;
		"Unknown") status="" ;;
esac

                        , "<fc=#c41449><fn=4>\xf2db</fn></fc> <total> <fn=5>\x25</fn> "
if [ "$capacity" -gt "90" ]; then
	icon="<fc=#c41449><fn=4>  </fn></fc>"
elif [ "$capacity" -le "90" ] && [ "$capacity" -gt "75" ]; then
	icon="<fc=#c41449><fn=4>  </fn></fc>"
elif [ "$capacity" -le "75" ] && [ "$capacity" -gt "10" ]; then
	icon="<fc=#c41449><fn=4>  </fn></fc>"
else
	icon="<fc=#c41449><fn=4>  </fn></fc>"
fi

charge_full_design=$(cat $battery/charge_full_design 2>/dev/null || cat $battery/energy_full_design)
charge_now=$(cat $battery/charge_now 2>/dev/null || cat $battery/energy_now 2>/dev/null) 
percentage=$(echo "100*$charge_now/$charge_full_design" | bc)
echo $icon$percentage%$status
