#!/bin/sh
d="$(date +"%G-%m-%d %R")"
sed -i "/Senast/!b;n;c$d" /home/ola/website/blog/index.html

if [ "$1" == "v" ]
then
  rsync -vrP --delete-after ~/website/blog/ root@olaberglund.xyz:/var/www/blog
else
  rsync -vrP --delete-after ~/website/blog/ root@olaberglund.xyz:/var/www/blog > /dev/null
fi



