#!/bin/sh
FILE="/home/ola/Documents/TODO.md"
OPTION=$1
if [ ${OPTION} ];
then
	case "$OPTION" in
		x)
			sed -i '0,/\[ /s/\[ /\[X/' $FILE
			;;
		a)
			echo "- [ ] "$2"" >> $FILE	
			;;
		d)
			nl $FILE
			read -p "Delete which task? (1-$(wc -l < $FILE), all: 0, all done: a ): " n
			if [ $n == 'a' ];
			then
				sed -i '/\[X/d' $FILE
			elif [ $n == 0 ];
			then
				> $FILE
			else
				sed -i $n'd' $FILE
			fi
			;;
	esac
fi
echo "$(<$FILE)"


